# Generated by Django 5.0.1 on 2024-04-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
